<? php
echo '<!DOCTYPE html>';
echo '<html lang="en" dir="ltr">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<link rel="stylesheet" href="main.css">';
echo '<link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">';
echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:800&display=swap" rel="stylesheet">';
echo '<script type="text/javascript" src="buttons.js"></script>';
echo '<script type="text/javascript" src="requests.js"></script>';
echo '<script type="text/javascript" src="control.js"></script>';
echo '<title>NetClaw | Online Claw Machine</title>';
echo '</head>';
echo '<body>';
echo '<div class="title">';
echo '<h1>NetClaw - Play a claw machine for free over the internet!</h1>';
echo '<h4>Support us on <a href="">Patreon</a></h4>';
echo '</div>';
echo '<div class="set">';
echo '';
echo '<div class="top-container">';
echo '<img class="stream" id="stream" style="-webkit-user-select: none;" src="http://ramcraft.ddns.net:8081/video" width="614" height="460">';
echo '</div>';
echo '<div class="controls">';
echo '<nav class="d-pad">';
echo '<a class="up" onmousedown="up()" onmouseup="stop()"></a>';
echo '<a class="right" onmousedown="right()" onmouseup="stop()"></a>';
echo '<a class="down" onmousedown="down()" onmouseup="stop()"></a>';
echo '<a class="left" onmousedown="left()" onmouseup="stop()"></a>';
echo '</nav>';
echo '<div class="circle-button">';
echo '<a onclick="drop()" class="circle-button" id="circlebutton">DROP</a>';
echo '</div>';
echo '<div class="switch-button">';
echo '<a onclick="swicherydoo()" class="switch-button">Switch Camera</a>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '</body>';
echo '';
echo '<footer>';
echo '<!-- Footer -->';
echo '<div class="bottom-container">';
echo '<br>';
echo '<a class="footer-link" href="https://www.instagram.com/charliekmcmahon">@charliekmcmahon</a>';
echo '<a class="footer-link" href="https://www.instagram.com/sams_amusements">| @sams_amusements</a>';
echo '<a class="footer-link" href="https://www.netclaw.com.au">| Website</a>';
echo '<p>© 2020 Charlie McMahon & Sam Pilgrim. All rights reserved.</p>';
echo '<p> We ❤️ arduino!</p>';
echo '<br>';
echo '</div>';
echo '</footer>';
echo '</html>';
echo '';
?>
